import test from 'node:test';
import assert from 'node:assert/strict';
import {readFile} from 'node:fs/promises';
import {ContractFactory,JsonRpcProvider,keccak256} from 'ethers';
import {Desk,money} from '../public-app/core.mjs';
const provider=new JsonRpcProvider('http://127.0.0.1:18545',undefined,{cacheTimeout:-1,batchMaxCount:1,pollingInterval:30});
const client=await provider.getSigner(3),freelancer=await provider.getSigner(4),outsider=await provider.getSigner(5);
const tokenArtifact=JSON.parse(await readFile(new URL('../out/DemoToken.sol/DemoToken.json',import.meta.url)));
const escrowArtifact=JSON.parse(await readFile(new URL('../out/Stagepay.sol/Stagepay.json',import.meta.url)));
const token=await new ContractFactory(tokenArtifact.abi,tokenArtifact.bytecode.object,client).deploy();await token.waitForDeployment();
const escrow=await new ContractFactory(escrowArtifact.abi,escrowArtifact.bytecode.object,client).deploy(await token.getAddress());await escrow.waitForDeployment();
const config={chainId:31337,escrow:await escrow.getAddress(),token:await token.getAddress(),escrowCodeHash:keccak256(await provider.getCode(await escrow.getAddress())),tokenCodeHash:keccak256(await provider.getCode(await token.getAddress()))};
const store=()=>{const map=new Map();return{getItem:k=>map.get(k)||null,setItem:(k,v)=>map.set(k,v)}};
const desk=new Desk(config,provider,store(),{allowLocal:true});
const counterparty=new Desk(config,provider,store(),{allowLocal:true});
const make=async()=>{await desk.send('mint',{amount:'10'},client);await desk.send('approve',{amount:'10'},client);return (await desk.send('create',{title:'Shared delivery',scope:'Build the club website.',freelancer:await freelancer.getAddress(),milestones:[{name:'Website',amount:'6'},{name:'Handover',amount:'4'}],acknowledge:true},client)).projectId;};
test('public release rejects local and mainnet configuration',()=>{assert.throws(()=>new Desk(config,provider,store()),/Sepolia/);assert.throws(()=>new Desk({...config,chainId:1},provider,store()),/Sepolia/);});
test('wrong deployment code blocks sending',async()=>{const d=new Desk({...config,escrowCodeHash:'0x'+'00'.repeat(32)},provider,store(),{allowLocal:true});await assert.rejects(()=>d.send('mint',{amount:'1'},client),/code/);assert.equal(d.read().pending,null);});
test('wallet flow checks shared hashes, roles, scope changes and settlement',async()=>{
 const projectId=await make();
 await assert.rejects(()=>counterparty.send('join',{projectId},freelancer),/matching scope/);
 await counterparty.import(desk.export(projectId));await counterparty.send('join',{projectId},freelancer);
 await assert.rejects(()=>desk.send('submit',{projectId,index:0,note:'Done',url:'https://example.com'},outsider),/belongs/);
 await counterparty.send('submit',{projectId,index:0,note:'Keyboard navigation works.',url:'https://example.com/website'},freelancer);
 await assert.rejects(()=>desk.send('accept',{projectId,index:0},client),/matching scope and delivery/);
 const edited=counterparty.export(projectId);edited.metadata.evidence[0].note='Different work';await assert.rejects(()=>desk.import(edited),/does not match/);
 await desk.import(counterparty.export(projectId));await desk.send('revision',{projectId,index:0,note:'Add mobile navigation.'},client);
 await counterparty.import(desk.export(projectId));assert.equal(counterparty.read().metadata[projectId].revisions[0].note,'Add mobile navigation.');assert.equal(await escrow.credits(await freelancer.getAddress()),0n);
 await counterparty.send('submit',{projectId,index:0,note:'Mobile navigation added.',url:'https://example.com/mobile'},freelancer);
 await desk.import(counterparty.export(projectId));await desk.send('accept',{projectId,index:0},client);
 assert.equal(await escrow.credits(await freelancer.getAddress()),money('6'));
 await assert.rejects(()=>desk.send('accept',{projectId,index:0},client));
 await desk.send('scope',{projectId,scope:'Keep the accepted site and add setup notes.'},client);
 await counterparty.import(desk.export(projectId));await counterparty.send('agree_scope',{projectId},freelancer);
 await desk.import(counterparty.export(projectId));assert.equal((await desk.project(projectId)).milestones[0].state,2);
 await counterparty.send('dispute',{projectId,note:'Agree on a smaller handover.'},freelancer);
 await desk.send('settle',{projectId,amount:'1'},client);const split=await counterparty.project(projectId);await assert.rejects(()=>counterparty.send('agree_settlement',{projectId,expectedNonce:String(split.proposalNonce-1n),expectedPayout:String(split.settlementPayout)},freelancer),/changed/);await counterparty.send('agree_settlement',{projectId,expectedNonce:String(split.proposalNonce),expectedPayout:String(split.settlementPayout)},freelancer);
 await desk.send('withdraw',{projectId},client);await counterparty.send('withdraw',{projectId},freelancer);
 assert.equal((await desk.project(projectId)).closed,true);assert.equal(await escrow.totalHeld(),0n);
});
test('lost wallet response is recovered without resending',async()=>{
 const before=await provider.getTransactionCount(await client.getAddress());
 const interrupted={provider,getAddress:()=>client.getAddress(),sendTransaction:async tx=>{await client.sendTransaction(tx);throw Error('Lost wallet response');}};
 await assert.rejects(()=>desk.send('mint',{amount:'1'},interrupted),/Lost/);assert.ok(desk.read().pending);
 await assert.rejects(()=>desk.send('mint',{amount:'1'},client),/pending/);
 await desk.reconcile();assert.equal(desk.read().pending,null);
 await desk.reconcile();assert.equal(await provider.getTransactionCount(await client.getAddress()),before+1);
});
test.after(()=>provider.destroy());
